

-- ─────────────────────────────────────────────────────────────────────────────
-- PUBLISHERS  (self-registering book publishers)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS publishers (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name   VARCHAR(255)    NOT NULL,
    email           VARCHAR(255)    NOT NULL,
    contact_person  VARCHAR(255)    NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    phone           VARCHAR(20)     DEFAULT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_publishers_email UNIQUE (email)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- EMPLOYEES  (bookfair staff & admins)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS employees (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)     NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    full_name       VARCHAR(255)    NOT NULL,
    role            VARCHAR(20)     NOT NULL DEFAULT 'EMPLOYEE',   -- EMPLOYEE | ADMIN
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_employees_username UNIQUE (username),
    CONSTRAINT chk_employee_role     CHECK  (role IN ('EMPLOYEE', 'ADMIN'))
);

-- ─────────────────────────────────────────────────────────────────────────────
-- STALLS  (physical booth positions on the floor map)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stalls (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(10)     NOT NULL,                      -- e.g. A1, B3
    size            VARCHAR(10)     NOT NULL,                      -- SMALL | MEDIUM | LARGE
    price_cents     INT             NOT NULL DEFAULT 0,            -- price in LKR cents
    width_meters    DECIMAL(5,2)    NOT NULL DEFAULT 3.00,
    height_meters   DECIMAL(5,2)    NOT NULL DEFAULT 3.00,
    position_x      INT             NOT NULL DEFAULT 0,
    position_y      INT             NOT NULL DEFAULT 0,
    reserved        BOOLEAN         NOT NULL DEFAULT FALSE,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_stalls_name    UNIQUE (name),
    CONSTRAINT chk_stall_size    CHECK  (size IN ('SMALL', 'MEDIUM', 'LARGE')),
    CONSTRAINT chk_price_positive CHECK (price_cents >= 0)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- RESERVATIONS  (a publisher books a stall)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reservations (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id    BIGINT          NOT NULL,
    stall_id        BIGINT          NOT NULL,
    qr_code         VARCHAR(36)     NOT NULL,                      -- UUID string
    status          VARCHAR(20)     NOT NULL DEFAULT 'CONFIRMED',  -- CONFIRMED | CANCELLED
    cancelled_at    TIMESTAMP       DEFAULT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_reservations_qr   UNIQUE (qr_code),
    CONSTRAINT uq_reservations_stall UNIQUE (stall_id),           -- one active reservation per stall
    CONSTRAINT chk_reservation_status CHECK (status IN ('CONFIRMED', 'CANCELLED')),

    CONSTRAINT fk_reservations_publisher
        FOREIGN KEY (publisher_id) REFERENCES publishers (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reservations_stall
        FOREIGN KEY (stall_id) REFERENCES stalls (id)
        ON DELETE CASCADE
);

-- ─────────────────────────────────────────────────────────────────────────────
-- GENRES  (literary genres a publisher sells – many-to-many via join table)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS genres (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,

    CONSTRAINT uq_genres_name UNIQUE (name)
);

-- join table: which publisher carries which genres
CREATE TABLE IF NOT EXISTS publisher_genres (
    publisher_id    BIGINT          NOT NULL,
    genre_id        BIGINT          NOT NULL,

    PRIMARY KEY (publisher_id, genre_id),

    CONSTRAINT fk_pg_publisher
        FOREIGN KEY (publisher_id) REFERENCES publishers (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pg_genre
        FOREIGN KEY (genre_id) REFERENCES genres (id)
        ON DELETE CASCADE
);

-- ─────────────────────────────────────────────────────────────────────────────
-- EMAIL_LOGS  (audit trail for every notification sent)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS email_logs (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id    BIGINT          NOT NULL,
    recipient_email VARCHAR(255)    NOT NULL,
    subject         VARCHAR(255)    NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'SENT',      -- SENT | FAILED
    error_message   VARCHAR(500)    DEFAULT NULL,
    sent_at         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_email_status CHECK (status IN ('SENT', 'FAILED')),

    CONSTRAINT fk_email_publisher
        FOREIGN KEY (publisher_id) REFERENCES publishers (id)
        ON DELETE CASCADE
);

-- ─────────────────────────────────────────────────────────────────────────────
-- QR_VERIFICATIONS  (log every time an employee scans a QR code at the gate)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS qr_verifications (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  BIGINT          NOT NULL,
    verified_by     BIGINT          NOT NULL,                      -- employee id
    verified_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_qrv_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservations (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_qrv_employee
        FOREIGN KEY (verified_by) REFERENCES employees (id)
        ON DELETE CASCADE
);


-- ============================================================================
-- 2. INDEXES
-- ============================================================================

-- Publishers ---------------------------------------------------------------
CREATE INDEX idx_publishers_email           ON publishers (email);
CREATE INDEX idx_publishers_business_name   ON publishers (business_name);

-- Employees ----------------------------------------------------------------
CREATE INDEX idx_employees_username         ON employees (username);
CREATE INDEX idx_employees_role             ON employees (role);

-- Stalls -------------------------------------------------------------------
CREATE INDEX idx_stalls_size                ON stalls (size);
CREATE INDEX idx_stalls_reserved            ON stalls (reserved);
CREATE INDEX idx_stalls_position            ON stalls (position_x, position_y);

-- Reservations -------------------------------------------------------------
CREATE INDEX idx_reservations_publisher     ON reservations (publisher_id);
CREATE INDEX idx_reservations_stall         ON reservations (stall_id);
CREATE INDEX idx_reservations_qr            ON reservations (qr_code);
CREATE INDEX idx_reservations_status        ON reservations (status);
CREATE INDEX idx_reservations_created       ON reservations (created_at DESC);

-- Genres -------------------------------------------------------------------
CREATE INDEX idx_genres_name                ON genres (name);
CREATE INDEX idx_pg_publisher               ON publisher_genres (publisher_id);
CREATE INDEX idx_pg_genre                   ON publisher_genres (genre_id);

-- Email Logs ---------------------------------------------------------------
CREATE INDEX idx_email_publisher            ON email_logs (publisher_id);
CREATE INDEX idx_email_sent_at              ON email_logs (sent_at DESC);

-- QR Verifications ---------------------------------------------------------
CREATE INDEX idx_qrv_reservation            ON qr_verifications (reservation_id);
CREATE INDEX idx_qrv_employee               ON qr_verifications (verified_by);


-- ============================================================================
-- 3. VIEWS
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- v_dashboard_stats  — single-row aggregate for the Employee Dashboard
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW v_dashboard_stats AS
SELECT
    (SELECT COUNT(*)            FROM stalls WHERE is_active = TRUE)                          AS total_stalls,
    (SELECT COUNT(*)            FROM stalls WHERE is_active = TRUE AND reserved = TRUE)      AS reserved_stalls,
    (SELECT COUNT(*)            FROM stalls WHERE is_active = TRUE AND reserved = FALSE)     AS available_stalls,
    (SELECT COUNT(*)            FROM publishers WHERE is_active = TRUE)                      AS total_publishers,
    (SELECT COUNT(*)            FROM reservations WHERE status = 'CONFIRMED')                AS total_reservations,
    CASE
        WHEN (SELECT COUNT(*) FROM stalls WHERE is_active = TRUE) = 0 THEN 0.0
        ELSE ROUND(
            (SELECT COUNT(*) FROM stalls WHERE is_active = TRUE AND reserved = TRUE) * 100.0
          / (SELECT COUNT(*) FROM stalls WHERE is_active = TRUE), 1)
    END                                                                                      AS occupancy_rate;

-- ─────────────────────────────────────────────────────────────────────────────
-- v_reservation_details  — flattened join used by employee reservation list
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW v_reservation_details AS
SELECT
    r.id                AS reservation_id,
    r.qr_code,
    r.status            AS reservation_status,
    r.created_at        AS reserved_at,
    r.cancelled_at,
    p.id                AS publisher_id,
    p.business_name,
    p.email             AS publisher_email,
    p.contact_person,
    s.id                AS stall_id,
    s.name              AS stall_name,
    s.size              AS stall_size,
    s.price_cents
FROM reservations r
    JOIN publishers p   ON r.publisher_id = p.id
    JOIN stalls s       ON r.stall_id     = s.id;

-- ─────────────────────────────────────────────────────────────────────────────
-- v_publisher_summary  — publisher list with reservation count & genres
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW v_publisher_summary AS
SELECT
    p.id                AS publisher_id,
    p.business_name,
    p.email,
    p.contact_person,
    p.phone,
    p.is_active,
    p.created_at,
    (SELECT COUNT(*) FROM reservations r
        WHERE r.publisher_id = p.id AND r.status = 'CONFIRMED')        AS reservation_count,
    (SELECT LISTAGG(g.name, ', ') WITHIN GROUP (ORDER BY g.name)
        FROM publisher_genres pg JOIN genres g ON pg.genre_id = g.id
        WHERE pg.publisher_id = p.id)                                   AS genres
FROM publishers p;

-- ─────────────────────────────────────────────────────────────────────────────
-- v_stall_map  — full stall grid data including current occupant
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW v_stall_map AS
SELECT
    s.id                AS stall_id,
    s.name              AS stall_name,
    s.size,
    s.price_cents,
    s.width_meters,
    s.height_meters,
    s.position_x,
    s.position_y,
    s.reserved,
    p.business_name     AS occupied_by
FROM stalls s
    LEFT JOIN reservations r ON r.stall_id = s.id AND r.status = 'CONFIRMED'
    LEFT JOIN publishers p   ON r.publisher_id = p.id
WHERE s.is_active = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- v_available_stalls  — quick lookup for the public stall listing
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW v_available_stalls AS
SELECT
    s.id,
    s.name,
    s.size,
    s.price_cents,
    s.width_meters,
    s.height_meters,
    s.position_x,
    s.position_y
FROM stalls s
WHERE s.is_active = TRUE AND s.reserved = FALSE;


-- ============================================================================
-- 4. SEED DATA  (for development / H2 in-memory bootstrap)
-- ============================================================================

-- Default admin employee (password: "admin123" — BCrypt hash placeholder)
INSERT INTO employees (username, password_hash, full_name, role)
VALUES ('admin', '$2a$10$placeholder_bcrypt_hash_admin123', 'System Admin', 'ADMIN');

INSERT INTO employees (username, password_hash, full_name, role)
VALUES ('staff1', '$2a$10$placeholder_bcrypt_hash_staff123', 'Fair Staff', 'EMPLOYEE');

-- Stalls  (4 rows × 5 cols = 20 stalls)
-- Row A  (y = 0)
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('A1', 'SMALL',   500000, 3.0, 3.0, 0, 0);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('A2', 'SMALL',   500000, 3.0, 3.0, 1, 0);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('A3', 'MEDIUM',  750000, 4.5, 3.0, 2, 0);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('A4', 'MEDIUM',  750000, 4.5, 3.0, 3, 0);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('A5', 'LARGE',  1000000, 6.0, 3.0, 4, 0);

-- Row B  (y = 1)
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('B1', 'SMALL',   500000, 3.0, 3.0, 0, 1);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('B2', 'SMALL',   500000, 3.0, 3.0, 1, 1);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('B3', 'MEDIUM',  750000, 4.5, 3.0, 2, 1);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('B4', 'MEDIUM',  750000, 4.5, 3.0, 3, 1);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('B5', 'LARGE',  1000000, 6.0, 3.0, 4, 1);

-- Row C  (y = 2)
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('C1', 'SMALL',   500000, 3.0, 3.0, 0, 2);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('C2', 'SMALL',   500000, 3.0, 3.0, 1, 2);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('C3', 'MEDIUM',  750000, 4.5, 3.0, 2, 2);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('C4', 'MEDIUM',  750000, 4.5, 3.0, 3, 2);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('C5', 'LARGE',  1000000, 6.0, 3.0, 4, 2);

-- Row D  (y = 3)
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('D1', 'SMALL',   500000, 3.0, 3.0, 0, 3);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('D2', 'SMALL',   500000, 3.0, 3.0, 1, 3);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('D3', 'MEDIUM',  750000, 4.5, 3.0, 2, 3);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('D4', 'MEDIUM',  750000, 4.5, 3.0, 3, 3);
INSERT INTO stalls (name, size, price_cents, width_meters, height_meters, position_x, position_y) VALUES ('D5', 'LARGE',  1000000, 6.0, 3.0, 4, 3);

-- Genre suggestions (seeded)
INSERT INTO genres (name) VALUES ('Fiction');
INSERT INTO genres (name) VALUES ('Non-Fiction');
INSERT INTO genres (name) VALUES ('Children''s Books');
INSERT INTO genres (name) VALUES ('Educational');
INSERT INTO genres (name) VALUES ('Comics & Graphic Novels');
INSERT INTO genres (name) VALUES ('Poetry');
INSERT INTO genres (name) VALUES ('Religious');
INSERT INTO genres (name) VALUES ('Self-Help');
INSERT INTO genres (name) VALUES ('Travel');
INSERT INTO genres (name) VALUES ('Cookbooks');
